services:
  - type: web
    name: flask-postgres-api
    runtime: python
    repo: https://github.com/UWI-Final-Exam-Scheduler/UWI-Final-Exam-Scheduler
    plan: free
    branch: main
    healthCheckPath: /healthcheck
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_config.py wsgi:app"
    envVars:
      - fromGroup: flask-postgres-api-settings

envVarGroups:
  - name: flask-postgres-api-settings
    envVars:
      - key: ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
