"""empty message

Revision ID: 0463f30e3c70
Revises: 7e217bf07dbb
Create Date: 2026-02-12 11:23:54.702321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0463f30e3c70'
down_revision = '7e217bf07dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('course_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('enrollment_course_name_fkey'), 'enrollment', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment', 'courses', ['course_id'], ['id'])
    op.drop_column('enrollment', 'course_name')
    op.add_column('students', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'students', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'student_id')
    op.add_column('enrollment', sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.create_foreign_key(op.f('enrollment_course_name_fkey'), 'enrollment', 'courses', ['course_name'], ['name'])
    op.drop_column('enrollment', 'course_id')
    # ### end Alembic commands ###
