"""empty message

Revision ID: 071bfb45b6ac
Revises: 75cd3e31a891
Create Date: 2026-03-28 15:09:31.084722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071bfb45b6ac'
down_revision = '75cd3e31a891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('abs_threshold', sa.Integer(), nullable=False),
    sa.Column('perc_threshold', sa.Float(), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_unique_constraint(None, 'exams', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='unique')
    op.drop_table('user_preference')
    # ### end Alembic commands ###
