"""empty message

Revision ID: 1cd4d035bca7
Revises: ee5af4c03063
Create Date: 2026-04-12 15:57:33.402499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd4d035bca7'
down_revision = 'ee5af4c03063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['id'])
    op.create_unique_constraint(None, 'clash_matrix', ['id'])
    op.create_unique_constraint(None, 'courses', ['courseCode'])
    op.create_unique_constraint(None, 'enrollments', ['id'])
    op.add_column('exams', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'exams', ['id'])
    op.create_foreign_key(None, 'exams', 'admins', ['admin_id'], ['id'])
    op.create_unique_constraint(None, 'students', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_constraint(None, 'exams', type_='unique')
    op.drop_column('exams', 'admin_id')
    op.drop_constraint(None, 'enrollments', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'clash_matrix', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
