"""empty message

Revision ID: 23b83e945c28
Revises: b76b9ab0c592
Create Date: 2026-03-23 09:40:00.879021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b83e945c28'
down_revision = 'b76b9ab0c592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['id'])
    op.create_unique_constraint(None, 'clash_matrix', ['id'])
    op.create_unique_constraint(None, 'courses', ['courseCode'])
    op.create_unique_constraint(None, 'enrollments', ['id'])
    op.create_unique_constraint(None, 'exams', ['id'])
    op.create_unique_constraint(None, 'students', ['student_id'])
    op.add_column('venues', sa.Column('current_occupancy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'current_occupancy')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'exams', type_='unique')
    op.drop_constraint(None, 'enrollments', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'clash_matrix', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
