"""allow null date on exams

Revision ID: 325c5b7efef1
Revises: d1d59e304aa1
Create Date: 2026-03-23 22:04:18.856856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325c5b7efef1'
down_revision = 'd1d59e304aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'date', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'date', nullable=False)
    # ### end Alembic commands ###
