"""empty message

Revision ID: 4c08d53f995f
Revises: 23b83e945c28
Create Date: 2026-03-23 10:06:05.335733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c08d53f995f'
down_revision = '23b83e945c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'current_occupancy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('current_occupancy', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
