"""empty message

Revision ID: 666828d15a69
Revises: ecc8fb0f6de1
Create Date: 2026-02-11 18:29:30.965188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666828d15a69'
down_revision = 'ecc8fb0f6de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    op.drop_table('students')
    # ### end Alembic commands ###
