"""empty message

Revision ID: 723e7b6e00cc
Revises: 4c08d53f995f
Create Date: 2026-03-23 13:20:13.722196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '723e7b6e00cc'
down_revision = '4c08d53f995f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'time',
               existing_type=postgresql.TIME(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'time',
               existing_type=sa.Integer(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
