"""empty message

Revision ID: 728d75154153
Revises: 1cd4d035bca7
Create Date: 2026-04-14 14:52:45.195854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728d75154153'
down_revision = '1cd4d035bca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['id'])
    op.create_unique_constraint(None, 'clash_matrix', ['id'])
    op.create_unique_constraint(None, 'courses', ['courseCode'])
    op.create_unique_constraint(None, 'enrollments', ['id'])
    op.create_unique_constraint(None, 'exams', ['id'])
    op.create_unique_constraint(None, 'students', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'exams', type_='unique')
    op.drop_constraint(None, 'enrollments', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'clash_matrix', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
