"""empty message

Revision ID: 75cd3e31a891
Revises: 325c5b7efef1
Create Date: 2026-03-23 22:10:45.665334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cd3e31a891'
down_revision = '325c5b7efef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('courseCode', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('exam_length', sa.Integer(), nullable=False),
    sa.Column('number_of_students', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseCode'], ['courses.courseCode'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_exams_date'), 'exams', ['date'], unique=False)
    op.create_index(op.f('ix_exams_venue_id'), 'exams', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_venue_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_date'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
