"""empty message

Revision ID: 7e217bf07dbb
Revises: 9a120d11c125
Create Date: 2026-02-11 19:35:47.912793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e217bf07dbb'
down_revision = '9a120d11c125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('course_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'enrollment', ['id'])
    op.drop_constraint(op.f('enrollment_course_id_fkey'), 'enrollment', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment', 'courses', ['course_name'], ['name'])
    op.drop_column('enrollment', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.create_foreign_key(op.f('enrollment_course_id_fkey'), 'enrollment', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'enrollment', type_='unique')
    op.drop_column('enrollment', 'course_name')
    # ### end Alembic commands ###
