"""empty message

Revision ID: 9575966b94bd
Revises: d8dbb63e52d0
Create Date: 2026-03-08 16:01:49.414939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9575966b94bd'
down_revision = 'd8dbb63e52d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clash_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course1', sa.String(length=20), nullable=False),
    sa.Column('course2', sa.String(length=20), nullable=False),
    sa.Column('clash_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course1'], ['courses.courseCode'], ),
    sa.ForeignKeyConstraint(['course2'], ['courses.courseCode'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course1', 'course2', name='course_clash'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'admins', ['id'])
    op.create_unique_constraint(None, 'courses', ['courseCode'])
    op.create_unique_constraint(None, 'enrollments', ['id'])
    op.create_unique_constraint(None, 'students', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'enrollments', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_table('clash_matrix')
    # ### end Alembic commands ###
