"""empty message

Revision ID: b76b9ab0c592
Revises: fc9621566b9c
Create Date: 2026-03-10 23:47:01.361564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76b9ab0c592'
down_revision = 'fc9621566b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'exams', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='unique')
    # ### end Alembic commands ###
