"""empty message

Revision ID: cd0ef1b061ad
Revises: f30848b53f08
Create Date: 2026-02-22 19:33:15.478693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0ef1b061ad'
down_revision = 'f30848b53f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'courses', ['courseCode'])
    op.create_unique_constraint(None, 'enrollment', ['id'])
    op.create_unique_constraint(None, 'students', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'enrollment', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_table('admin')
    # ### end Alembic commands ###
