"""exams table with integer time

Revision ID: d1d59e304aa1
Revises: 723e7b6e00cc
Create Date: 2026-03-23 13:23:25.744443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d59e304aa1'
down_revision = '723e7b6e00cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('courseCode', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('exam_length', sa.Integer(), nullable=False),
    sa.Column('number_of_students', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseCode'], ['courses.courseCode'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_exams_date'), 'exams', ['date'], unique=False)
    op.create_index(op.f('ix_exams_venue_id'), 'exams', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_venue_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_date'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
