"""empty message

Revision ID: d8dbb63e52d0
Revises: 36a5d6642244
Create Date: 2026-03-02 02:07:45.493965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dbb63e52d0'
down_revision = '36a5d6642244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('admin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_pkey')),
    sa.UniqueConstraint('id', name=op.f('admin_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('admins')
    # ### end Alembic commands ###
