"""empty message

Revision ID: dc41d8aec550
Revises: 9575966b94bd
Create Date: 2026-03-08 22:23:28.276048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc41d8aec550'
down_revision = '9575966b94bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clash_matrix', ['id'])
    op.drop_constraint(op.f('courses_name_key'), 'courses', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('courses_name_key'), 'courses', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'clash_matrix', type_='unique')
    # ### end Alembic commands ###
