"""empty message

Revision ID: e2b1599b46b2
Revises: 0463f30e3c70
Create Date: 2026-02-12 11:39:48.837238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b1599b46b2'
down_revision = '0463f30e3c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('student_course', 'enrollment', ['student_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_course', 'enrollment', type_='unique')
    # ### end Alembic commands ###
