"""allow null venue_id on exams

Revision ID: ee5af4c03063
Revises: df4069622573
Create Date: 2026-04-04 16:25:35.161085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5af4c03063'
down_revision = 'df4069622573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'enrollments', ['id'])
    op.alter_column('exams', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'enrollments', type_='unique')
    # ### end Alembic commands ###
