"""empty message

Revision ID: fc9621566b9c
Revises: 22b00119657e
Create Date: 2026-03-10 23:02:14.933490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9621566b9c'
down_revision = '22b00119657e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseCode', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('exam_length', sa.Integer(), nullable=False),
    sa.Column('number_of_students', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseCode'], ['courses.courseCode'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_exams_date'), 'exams', ['date'], unique=False)
    op.create_index(op.f('ix_exams_venue_id'), 'exams', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_venue_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_date'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
