"""empty message

Revision ID: fedfc3d8e496
Revises: 56c9f07124b8
Create Date: 2026-02-11 19:12:23.806963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedfc3d8e496'
down_revision = '56c9f07124b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'enrollment', ['id'])
    op.drop_constraint(op.f('enrollment_user_id_fkey'), 'enrollment', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment', 'students', ['student_id'], ['id'])
    op.drop_column('enrollment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.create_foreign_key(op.f('enrollment_user_id_fkey'), 'enrollment', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'enrollment', type_='unique')
    op.drop_column('enrollment', 'student_id')
    # ### end Alembic commands ###
