"""empty message

Revision ID: ff5a8511e420
Revises: c2fd189c7ec4
Create Date: 2026-02-23 22:16:37.413071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5a8511e420'
down_revision = 'c2fd189c7ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin', ['id'])
    op.create_unique_constraint(None, 'courses', ['courseCode'])
    op.create_unique_constraint(None, 'enrollments', ['id'])
    op.create_unique_constraint(None, 'students', ['student_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'enrollments', type_='unique')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_constraint(None, 'admin', type_='unique')
    # ### end Alembic commands ###
